name: CI

on:
  push:
    paths:
      - '**.py'
      - '**.f90'
      - '**.toml'
      - '**.yml'

jobs:
  RunTests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.14"]
        exclude:
          - os: macos-latest
            python-version: '3.9'
        include:
          - python-version: '3.9'
            module-versions: "numpy==1.21 scipy==1.9 sympy==1.9 matplotlib==3.3 pandas==1.3 jinja2 joblib==1.1 threadpoolctl gmpy2 numba==0.53 meson ninja pytest setuptools==69"
          - python-version: '3.14'
            module-versions: "numpy==2.3.5 scipy sympy matplotlib pandas jinja2 joblib threadpoolctl gmpy2 numba meson ninja pytest"
        toolchain:
          - {compiler: gcc, version: 'latest'}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Fortran Compiler
        uses: fortran-lang/setup-fortran@v1
        if: runner.os == 'MacOS'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.module-versions }}
          pip install .
      - name: Run tests
        run: yes 2>/dev/null | pytest -s --durations=0 testing/
        if: runner.os != 'Windows'
      - name: Run tests windows
        run: echo 'N' | pytest -s --durations=0 testing/
        if: runner.os == 'Windows'
      - name: Upload log files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-logfiles_${{runner.os}}_${{matrix.python-version}}
          path: |
            regressiontests/poly.log
            regressiontests/dragiso.log
            regressiontests/drag/dragsemi.log
            regressiontests/LT_exp/LT.log

